#!/usr/bin/env bash
# Bash script that displays a list of current running processes
# Show all processes, for all users, including those which might not have a TTY
# Displays in a user-oriented format
# Show process hierarchy

ps -e u
