#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
hr=0
while (("$hr" <= 12))
do
	echo "Hour: $hr"
	min=1
	while (("$min" < 60))
	do
		echo $min
		((min++))
	done
	((hr++))
done
